### ISSUE TITLE
Convert to Own Icons & Colors

### ISSUE THREAD

**Issue by pulp-pixel** [envybros/envybros.com#19]
#18 <- 여기 내용으로 어떤 파일들을 수정해야 하는지 알았으므로,,

이제 자체 SVG Image 및 Icons를 활용해서 내용 업데이트
(최대한 많이 만들고, 색상 또한 업데이트)

**Comment by pablo-stelsi** [comment]
[canva 링크](https://www.canva.com/logos/) <- 여기 사이트 써도 될 것 같은데?
